[package]
name = "procmaps"
version = "0.3.0"
authors = ["William Woodruff <william@yossarian.net>"]
edition = "2018"
description = "Python bindings for procmaps.rs"
homepage = "https://github.com/woodruffw/procmaps.py"
repository = "https://github.com/woodruffw/procmaps.py"
readme = "README.md"
license = "MIT"

[package.metadata.release]
no-dev-version = true
disable-publish = true # handled by GitHub Actions

[package.metadata.maturin]
classifier = [
  "Programming Language :: Rust",
  "Operating System :: POSIX :: Linux",
]

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
pyo3 = { version = "0.12", features = ["extension-module"] }
rsprocmaps = "0.3"
