on:
  push:
    tags:
      - 'v*'

name: release

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'rc') }}

  build-dists:
    name: build dists for publishing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: build dists
        run: make dist

      - name: upload dists
        uses: actions/upload-artifact@v3
        with:
          name: procmaps-py-dists
          path: dist/

  pypi:
    name: upload release to PyPI
    needs:
      - create-release
      - build-dists
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # Used for OIDC publishing.
      # Used to sign the release's artifacts with sigstore-python.
      id-token: write

      # Used to attach signing artifacts to the published release.
      contents: write

    steps:
      - name: fetch dists
        uses: actions/download-artifact@v3
        with:
          name: procmaps-py-dists
          path: dist/

      - name: publish
        uses: pypa/gh-action-pypi-publish@v1.8.4

      - name: sign
        uses: sigstore/gh-action-sigstore-python@v1.2.2
        with:
          inputs: ./dist/*.tar.gz ./dist/*.whl
          release-signing-artifacts: true
          bundle-only: true
